// LOCALSTORAGE
export const STORAGE_LIST_KEY = 'STORAGE_LIST_KEY';

// HTML
export const TASK_CONTAINER_ID = 'LIST_CONTAINER_ID';
export const ADD_TASK_FORM_ID = 'ADD_TASK_FORM_ID';
export const ADD_TASK_TEXT_FIELD_ID = 'ADD_TASK_TEXT_FIELD_ID';

export const TASK_ELEMENT_SHOPIFY_BIND_CLASS =
  'TASK_ELEMENT_SHOPIFY_BIND_CLASS';
export const TASK_ELEMENT_SHOPIFY_DRAG_CLASS =
  'TASK_ELEMENT_SHOPIFY_DRAG_CLASS';

export const TASK_ELEMENT_EVENT_BIND_CLASS = 'TASK_ELEMENT_EVENT_BIND_CLASS';
export const TASK_ELEMENT_INPUT_CLASS = 'TASK_ELEMENT_INPUT_CLASS';
export const TASK_ELEMENT_LABEL_CLASS = 'TASK_ELEMENT_LABEL_CLASS';
export const TASK_ELEMENT_SPAN_CLASS = 'TASK_ELEMENT_SPAN_CLASS';
export const TASK_ELEMENT_DELETE_CLASS = 'TASK_ELEMENT_DELETE_CLASS';

export const CONFIRM_DELETE_DIALOG_ID = 'CONFIRM_DELETE_DIALOG_ID';
export const CONFIRM_DELETE_DIALOG_CLOSE_BUTTON_ID =
  'CONFIRM_DELETE_DIALOG_CLOSE_BUTTON_ID';
export const CONFIRM_DELETE_DIALOG_YES_BUTTON_ID =
  'CONFIRM_DELETE_DIALOG_YES_BUTTON_ID';
export const CONFIRM_DELETE_DIALOG_NO_BUTTON_ID =
  'CONFIRM_DELETE_DIALOG_NO_BUTTON_ID';
export const CONFIRM_DELETE_DIALOG_TASK_TEXT_PARAGRAPH_ID =
  'CONFIRM_DELETE_DIALOG_TASK_TEXT_PARAGRAPH_ID';
